include:
  - board: nice_nano//zmk
    shield: splitkb_aurora_sweep_left
  - board: nice_nano//zmk
    shield: splitkb_aurora_sweep_right
  - board: nice_nano//zmk
    shield: cradio_left
  - board: nice_nano//zmk
    shield: cradio_right
